### PR TITLE
Fix minor bugs in encryption_service.dart

### LINKED ISSUE #321: Analyse decryption issues
Analyse and come up with approach for below scenarios

- [ ] Public key changes
- [ ] Encryption key changes

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

File: at_client/lib/src/service/encryption_service.dart [hunk 1]
```diff
@@ -119,6 +126,11 @@ class EncryptionService {
   /// Used for local lookup @bob:phone@alice
   Future<String?> decryptLocal(String? encryptedValue, String? currentAtSign,
       String sharedWithUser) async {
+    if (encryptedValue == null || encryptedValue.isEmpty) {
```
Comment (murali-shris) [inline at_client/lib/src/service/encryption_service.dart:129]: can we also log in the caller when encryptedValue is null.so we will know for which key the encryptedValue is null

**Review by murali-shris — APPROVED** [review]
