### PR TITLE
fix: ignore notifications received offline

### LINKED ISSUE #911: forText notifications with StrategyEnum.latest do not provide just the latest notification.
**Describe the bug**
Old notifications appearing as atsign connects

**To Reproduce**
1. First I run the MWC demo code and clients (using the iot-expo-colin branch)
2. Then I sent some readings
3. And then 'switched atSign to an atsign that also was sent the notifications
4. Old notifications appear on reconnect
5. These old notifcations can build up if the atSign is not used for a while and notifications have come in. Resulting in an unrecoverable state in the worst case

**Expected behavior**
Notifications should not be stored and only new notifcations be sent onward 

**Screenshots**

https://user-images.githubusercontent.com/6131216/190032985-70f4d475-adc6-40b0-a2cc-956d8e679f27.mp4

Video'd session was using the trunk branch for the secondary (in my dess infra)

**Were you using an atApplication when the bug was found?**
  - MWC Demo

**Additional context**
The video has more context. This is P1 as it can lead to bad things!

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- Add a new preference to the AtClientPreferences to optionally ignore the notifications received when offline upon the subsequent restarts.

**- How I did it**
- In AtClientPreferences add a boolean variable `fetchOfflineNotifications` which defaults to true (the existing behaviour). Optionally can be set to false to ignore the notification received when offline.

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by sitaram-kalluri** [comment]
Tests ran in local with changes:

```
**Monitor first run**
----------------------
/home/sitaram/DevTools/flutter-sdk/flutter/bin/cache/dart-sdk/bin/dart run test -r json /home/sitaram/IdeaProjects/atsign/core/at_client_sdk/at_client/test/samples/monitor/monitor_single_subscription_regex.dart
Testing started at 10:19 am ...
INFO|2022-09-15 10:19:55.039054|HiveBase|commit_log_225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:19:55.059807|HiveBase|225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:19:55.254544|Monitor|monitor started for @murali with last notification time: null 
alice notification received: AtNotification{id: 5485a80e-9a27-446e-b2b6-57d6d7298bee, key: @murali:text-0, from: @sitaram, to: @murali, epochMillis: 1663217358396, value: null, operation: update}
alice notification received: AtNotification{id: 542f1448-e585-417e-8b0a-d090a43def1b, key: @murali:text-1, from: @sitaram, to: @murali, epochMillis: 1663217403389, value: null, operation: update}
alice notification received: AtNotification{id: 80f2f235-b2a9-42d0-8c52-373121921570, key: @murali:text-2, from: @sitaram, to: @murali, epochMillis: 1663217404925, value: null, operation: update}
alice notification received: AtNotification{id: 69bc8b64-ab1d-4775-b074-3acd0055d0b5, key: @murali:text-3, from: @sitaram, to: @murali, epochMillis: 1663217406501, value: null, operation: update}
alice notification received: AtNotification{id: -1, key: statsNotification.@murali, from: @murali, to: @murali, epochMillis: 1663217408798, value: 2, operation: update}
alice notification received: AtNotification{id: 91171f82-27e5-4dd8-8a33-2819d5596ada, key: @murali:text-4, from: @sitaram, to: @murali, epochMillis: 1663217407986, value: null, operation: update}

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)


**Monitor second run - client restarted with setting 'fetchOfflineNotifications' to false. So notifications from text-5 to text-15 are ignored.**
------------------------------------------------------------------------------------------------------------------------------------------------------
/home/sitaram/DevTools/flutter-sdk/flutter/bin/cache/dart-sdk/bin/dart run test -r json /home/sitaram/IdeaProjects/atsign/core/at_client_sdk/at_client/test/samples/monitor/monitor_single_subscription_regex.dart
Testing started at 10:20 am ...
INFO|2022-09-15 10:20:27.298624|HiveBase|commit_log_225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:20:27.318969|HiveBase|225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:20:27.513581|Monitor|monitor started for @murali with last notification time: null 
alice notification received: AtNotification{id: 643c2773-83a8-4d81-941e-024918dfcd44, key: @murali:text-16, from: @sitaram, to: @murali, epochMillis: 1663217426296, value: null, operation: update}
alice notification received: AtNotification{id: cd5f9ae2-9105-4b5c-970b-64da4509c81f, key: @murali:text-17, from: @sitaram, to: @murali, epochMillis: 1663217427830, value: null, operation: update}
alice notification received: AtNotification{id: 18847725-47c6-4601-abad-763bc1f8f8d9, key: @murali:text-18, from: @sitaram, to: @murali, epochMillis: 1663217429350, value: null, operation: update}
alice notification received: AtNotification{id: 5db81c95-d1fc-4d8d-a230-ceaaa1f95cd9, key: @murali:text-19, from: @sitaram, to: @murali, epochMillis: 1663217430928, value: null, operation: update}
alice notification received: AtNotification{id: e920ccb8-35b5-48f8-b63d-3362a0d2b9f4, key: @murali:text-20, from: @sitaram, to: @murali, epochMillis: 1663217432454, value: null, operation: update}

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)


**Monitor second run - client restarted with setting 'fetchOfflineNotifications' to true. So lastNotificationTime is sent to secondary and notification received are fetched.**
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/home/sitaram/DevTools/flutter-sdk/flutter/bin/cache/dart-sdk/bin/dart run test -r json /home/sitaram/IdeaProjects/atsign/core/at_client_sdk/at_client/test/samples/monitor/monitor_single_subscription_regex.dart
Testing started at 10:20 am ...
INFO|2022-09-15 10:20:54.252507|HiveBase|commit_log_225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:20:54.273253|HiveBase|225ec42f3539301ac4076ab97420deb3f2727fab2343674c777eda4885419c79 initialized successfully 
INFO|2022-09-15 10:20:54.364573|Monitor|starting monitor for @murali with lastNotificationTime: 1663217432454 
INFO|2022-09-15 10:20:54.509759|Monitor|monitor started for @murali with last notification time: 1663217432454 
alice notification received: AtNotification{id: 28d9e138-39ce-4d35-8809-d9526dbbb1cc, key: @murali:text-21, from: @sitaram, to: @murali, epochMillis: 1663217433981, value: null, operation: update}
alice notification received: AtNotification{id: 5201c294-d158-4dad-a6f5-2d8164234b24, key: @murali:text-22, from: @sitaram, to: @murali, epochMillis: 1663217435499, value: null, operation: update}
alice notification received: AtNotification{id: a6e5bdaf-d2f5-4b64-ba47-47272ff639a1, key: @murali:text-23, from: @sitaram, to: @murali, epochMillis: 1663217437032, value: null, operation: update}

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)


```

File: at_client/lib/src/preference/at_client_preference.dart [hunk 1]
```diff
@@ -82,6 +82,10 @@ class AtClientPreference {
   /// * When set to false keys such as public:foo@alice or @bob:foo@alice will not be rejected
   /// * Defaults to true, as applications should always be placing keys within a namespace
   bool enforceNamespace = true;
+
+  /// Fetch the notifications received when the client is offline. Defaults to true.
+  /// Set to false to ignore the notifications received when device is offline.
+  bool fetchOfflineNotification = true;
```
Comment (VJag) [inline at_client/lib/src/preference/at_client_preference.dart]: should we just call it "latest"?

**Review by VJag — DISMISSED** [review]

**Comment by sitaram-kalluri** [comment]
Skipping the notify test because the test is failing due to timezone issue:

Attaching the log below

```
Epoch Mills from client : 1663241296123 /// /// Thu Sep 15 2022 16:58:16

ce2e2_secondary.1.cuthczzaiu9e@cicd2x64    | INFO|2022-09-15 11:28:22.817005|InboundListener|RCVD: [_3cc94e4a-c969-44a7-9279-3f1ea909f86e] monitor:1663233673909 /// Thu Sep 15 2022 14:51:13
ce2e2_secondary.1.cuthczzaiu9e@cicd2x64    | 

/// Notification time stamp on receiver secondary - Thu Sep 15 2022 15:45:24
ce2e2_secondary.1.cuthczzaiu9e@cicd2x64    | INFO|2022-09-15 11:28:22.817914|InboundConnectionImpl|SENT: [_3cc94e4a-c969-44a7-9279-3f1ea909f86e] notification: {"id":"
af7e1999-6e10-4a80-8dc6-c6d0b2b88cc7","from":"@ce2e1","to":"@ce2e2","key":"@ce2e2:t3XmJmqbd19cJUsHx6gkh/3+FDPsEtEsTu5kRMWq2zk=","value":null,"operation":"update","epo
chMillis":1663236924114,"messageType":"MessageType.text","isEncrypted":true} /// Thu Sep 15 2022 15:45:24


ce2e2_secondary.1.cuthczzaiu9e@cicd2x64    | INFO|2022-09-15 11:28:24.425341|InboundListener|RCVD: [_073cf68a-3b5c-4707-90eb-86b8869a4290] monitor:1663241296123 /// Thu Sep 15 2022 16:58:16
```

**Review by murali-shris — APPROVED** [review]
