### PR TITLE
fix: namespace in atkey overrides the namespace in preference

### LINKED ISSUE #841: Atkey namespace overridden by AtClientPreference namespace
### Describe the bug

This happened when we tried deleting wavi image key from Buzz app.

In Buzz, we created following atKey with `wavi` as namespace
```
 atKey = AtKey()
      ..key = "image"
      ..sharedWith = null
      ..namespace = 'wavi'
      ..metadata = metaData;
```

when we called delete operation on it, the namespace was overridden by the one added in `AtClientPreference`.

Thus the actual key was not deleted.

### Steps to reproduce

1. Run Buzz app and try to delete image with above-mentioned code.

### Expected behavior

- the namespace added in atKey should not have been overridden.

### Screenshots

_No response_

### Smartphones

- iPhone 12 simulator

### Were you using an atApplication when the bug was found?

Buzz

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
1. When atKey has a different namespace from the namespace in the AtClientPreference, set the namespace from the atKey to the key.
2. Update the CHANGELOG.md
3. Update the version in pubspec.yaml and AtClientConfig

**- How I did it**
1. In the atClient-> _delete method, use `AtClientUtil.getKeyWithNameSpace` instead of `_getKeyWithNamespace` in AtClientImpl

**- How to verify it**
1. Added unit test, functional test and an end2end test to verify the namespace from atKey overrides the namespace in the preference.

**- Description for the changelog**
- fix: Enable AtKey.namespace overrides the namespace in AtClientPreference in AtClient delete method

### CODE REVIEW

**Comment by gkc** [comment]
@kalluriramkumar Can you explain what the root cause of the issue was please? Either here, or in the bug report ticket

File: packages/at_client/lib/src/client/at_client_impl.dart [hunk 1]
```diff
@@ -214,44 +214,31 @@ class AtClientImpl implements AtClient {
...
-      bool namespaceAware = true,
-      bool isLocal = false}) async {
+  Future<bool> _delete(AtKey atKey) async {
+    // If metadata is null, initialize metadata
+    atKey.metadata ??= Metadata();
     String keyWithNamespace;
-    if (namespaceAware) {
-      keyWithNamespace = _getKeyWithNamespace(key);
+    if (atKey.metadata!.namespaceAware) {
+      keyWithNamespace = AtClientUtil.getKeyWithNameSpace(atKey, _preference!);
```
Comment (gkc) [inline packages/at_client/lib/src/client/at_client_impl.dart:229]: I notice that _getKeyWithNamespace is still called from the `notifyChange` and `putMeta` methods ... do those parts of the code also need to be looked at?

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_client/lib/src/client/at_client_impl.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: `notifyChange` is currently not in use and it has no usage in at_client. The code is moved to `notification_service_impl.notify` method. Perhaps, can we mark `notifyChange` as deprecated? and We have update in `putMeta` method.

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar Can you explain what the root cause of the issue was please? Either here, or in the bug report ticket

@gkc: At the moment, the delete method fetches the namespace from the `AtClientPreference.namespace` only. we cannot override the namespace of a specific key.

One use case of setting a different namespace for a specific key is, we fetch the public info (firstName, lastName and profile pic) from the wavi and display it in the buzz app. Now, If someone wants to update/delete the profile pic from buzz app, we have to form a key with the namespace `wavi` in the buzz app.

File: packages/at_client/lib/src/client/at_client_impl.dart (hunk 1 above)
Comment (gkc) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: Yes notifyChange should be marked deprecated

Comment (gkc) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: I don't understand what you mean by "We have update in putMeta method"?

Comment (sitaram-kalluri) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: @gkc: Sorry for the typo. I meant it has to be updated in the putMeta method also. Shall I make the changes in the same PR or can I create a separate ticket and do the changes.

Comment (gkc) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: OK I see. Up to you re separate ticket

**Review by gkc — APPROVED** [review]

File: packages/at_client/lib/src/client/at_client_impl.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/client/at_client_impl.dart:229]: @gkc: Since this is tested and apps team need the changes, merging these changes. Will make the changes for putMeta in separate PR.
