### PR TITLE
fix: throw exception when an empty string is passed as atsign to setCurrentAtsign()

### LINKED ISSUE #657: setCurrentAtSign allows empty string
**Describe the bug**
AtClientManager.setCurrentAtSign allows empty string argument for atSign. This results, later, in exceptions which are not obvious to diagnose. 

**Expected behavior**
AtClientManager.setCurrentAtSign should immediately reject malformed atSign arguments with an exception 

**Additional context**
See also https://github.com/atsign-foundation/at_client_sdk/issues/655

### PR DESCRIPTION
**Pull request by purnimavenkatasubbu**
**- What I did**
throw an exception if an empty string is passed as an atsign in setCurrentAtsign()

**- How I did it**
Added AtUtils.fixAtSign() which validates the atsign

**- How to verify it**
at_exception_test.dart should pass

**- Description for the changelog**
Throws an exception if an empty string is passed as an atsign in setCurrentAtsign()

### CODE REVIEW

File: at_functional_test/test/at_exception_test.dart [hunk 1]
```diff
@@ -36,4 +36,10 @@ void main() {
     expect(() async => await atClient.get(key),
         throwsA(predicate((dynamic e) => e is AtClientException)));
   });
+
+   test('Verify empty atsign throws exception', () async {
```
Comment (murali-shris) [inline at_functional_test/test/at_exception_test.dart]: this test can be moved to at_client unit tests

**Review by sitaram-kalluri — APPROVED** [review]

**Review by gkc — APPROVED** [review]
