### PR TITLE
fix: ensure key exchange functions properly when a sync service is not being used

### LINKED ISSUE #1041: Symmetric encryption keys always need to go to atServer first
### Describe the bug

Current logic when getting the shared encryption key to encrypt data for
sharing with another atSign
- get my copy (looks in local, looks in remote)
- if I don't have a copy, make a new one
- when making a new one
  - store their copy to local
  - store my copy to local
  - if their copy not sync'd, send it to atServer

Problems with this:
- Dependent on sync working in order to store my copy to atServer
  - So a client which doesn't sync will never send my copy to atServer
  - And if such a client resets local storage then my copy is lost
  - Multiple clients which do not sync will all cut their own encryption keys
- Takes a roundabout way of getting their copy out to atServer - i.e.
  instead of just storing to atServer, it stores locally and later checks if
  it has been sync'd, and then sends to atServer if it hasn't been sync'd

### Steps to reproduce

- Run new servers for alice and bob. Run an alice client with no sync, then share data with bob. `@bob:shared_key@alice` never reaches atServer
- Run new servers for alice and bob. Run multiple alice clients with no sync, each sharing data with bob - they will each create a new symmetric key
- Run new servers for alice and bob. Run an alice client with no sync, then share data with bob. `@bob:shared_key@alice` never reaches atServer. Remove alice's local storage and repeat - observe that a new symmetric key is created and once again does not go to atServer

### Expected behavior

Desired logic
1. My copy not found in local, atServer unavailable ? => exception
2. My copy not found in local, not found in atServer => create new
  and then (**changed**) save to atServer, then local
2a. If atServer rejects the 'new' record because another client has just created a 'new' record, then fetch the existing value from the atServer
3. **changed** My copy not found in local, found in atServer => save to local
4. My copy found in local? Great.

Need to also verify that 'their' copy is in a good state
1. **changed** Their copy not found local, not found in atServer ==> save to atServer, and then
  to local
2. **changed** Their copy not found local, but found in atServer => save to local

Once desired logic implemented, this means that both my copy and their
copy can only ever get into my local storage *after* they are already in
the atServer, either because (1) I created it, and my sequence is to create
remote first then store local, or (2) another client created it, I fetched
it from remote then stored local, or (3) another client created it and it
automatically got to my local storage via sync

**Note** Step 2a above addresses another issue with all of this which is the race condition between multiple clients all attempting at the same time to shared data with another atSign for the first time. This requires an atServer change which will happen swiftly after this change.

### PR DESCRIPTION
**Pull request by gkc**
**- What I did**
fix: resolves #1041

**- How I did it**
- Implemented new logic in abstract_atkey_encryption.dart as specified in #1041
- Tweaked mockLocalSecondary and mockRemoteSecondary setup in unit tests in encryption_service_test.dart
- Tweaked mockLocalSecondary and mockRemoteSecondary setup in some other unit tests
- No other actual changes (just fixed some unnecessary import statements from a few files)
- New test cases which verify that the key exchange is working as intended in all scenarios

**- How to verify it**
Tests should pass

**- Description for the changelog**
fix: ensure key exchange functions properly when no sync service is being used

### CODE REVIEW

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 1]
```diff
@@ -29,104 +27,76 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
         'AbstractAtKeyEncryption (${_atClient.getCurrentAtSign()})');
   }
 
-  @visibleForTesting
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:32]: This was being used to try to ensure something had been sync'd. Removing as now obsolete.

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 2]
```diff
@@ -29,104 +27,76 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
...
-    if (encryptedSharedKey.isNull) {
-      encryptedSharedKey =
-          EncryptionUtil.encryptKey(sharedKey, sharedWithPublicKey);
-    }
-    // Check if the encryptedSharedKey is synced to remote secondary
-    // If not synced, update the key to remote secondary directly
-    if (!(await isEncryptedSharedKeyInSync(atKey))) {
-      await updateEncryptedSharedKeyToSecondary(atKey, encryptedSharedKey,
-          secondary: _atClient.getRemoteSecondary());
+      _sharedKey = await createMyCopyOfSharedSymmetricKey(atKey);
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:45]: Created new method `createMyCopyOfSharedSymmetricKey` for readability of this (encrypt) method and clarity around the new logic

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 3]
```diff
@@ -29,104 +27,76 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
...
+  /// Fetches existing shared symmetric key
+  /// - Look first in local storage.
+  /// - If not found in local storage, tries atServer
+  /// - If not found in atServer, return empty string
+  /// - If found on atServer, save to local
+  /// - If found existing in either local or atServer, decrypt it and return
   /// Throws [KeyNotFoundException] if the encryptionPrivateKey is not found.
-  Future<String> getSharedKey(AtKey atKey) async {
+  ///
+  Future<String> getMyCopyOfSharedSymmetricKey(AtKey atKey) async {
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:66]: Renamed for clarity

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 4]
```diff
@@ -29,104 +27,76 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
...
+          EncryptionUtil.md5CheckSum(await _getSharedWithPublicKey(atKey));
     }
   }
 
-  /// Fetches the shared key in the local secondary
-  /// If not found, fetches in the remote secondary
-  /// If found, returns the decrypted sharedKey.
-  ///
-  /// If shared_key is not found in local secondary and remote secondary, returns an empty string
-  ///
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:105]: New method comment below describes the desired new logic.

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 5]
```diff
@@ -159,6 +133,100 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
     }
   }
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:135]: New method comment below describes the desired new logic for if / when a new shared symmetric key needs to be created

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 6]
```diff
@@ -201,59 +269,62 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
...
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:270]: renamed _storeSharedKey and removed `shouldSync` parameter as all of this stuff is no longer dependent on sync in any way

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 7]
```diff
@@ -266,6 +337,6 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
       ..sharedBy = atKey.sharedBy
       ..ttr = 3888000
       ..value = encryptedSharedKeyValue;
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:339]: `sync: false` now, because we are always saving to atServer first anyway

File: packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart [hunk 8]
```diff
@@ -201,59 +269,62 @@ abstract class AbstractAtKeyEncryption implements AtKeyEncryption {
...
+      // ignore: unused_catch_clause, empty_catches
+    } on KeyNotFoundException catch (ignore) {}
+    if (myCopy == 'data:null') {
+      myCopy = null;
+    }
+    if (myCopy != null && myCopy.startsWith('data:')) {
+      myCopy = myCopy.replaceFirst('data:', '');
+    }
+    return myCopy;
   }
```
Comment (gkc) [inline packages/at_client/lib/src/encryption_service/abstract_atkey_encryption.dart:306]: The next bit of diff here is kind of rubbish - I removed an obsolete method called isEncryptedSharedKeyInSync. Unrelated, I added a new method called _getTheirEncryptedCopyOfSharedSymmetricKey

**Comment by gkc** [comment]
Some new unit tests to be added but is probably good enough now to start testing from other places via dependency override to this branch

**Review by cconstab — DISMISSED** [review]
Everything as we discussed thank you...

The only possible improvement could be after getting the local AES key and if that fails to decrypt then to circle back and pull from secondary and retry if the keys are different.

I have seen this went a sync has happened in the dim past and the atSIgn has been reset for example and the local AES key is wrong. The way to get out of that loop currently is pretty harsh, delete the local storage.

This I think is now pretty unlikely/is not a problem now, but I thought I should mention it..

Colin

**Review by sitaram-kalluri — DISMISSED** [review]

**Comment by gkc** [comment]
Hi @sitaram-kalluri and @cconstab ... I've finally got the new unit tests to how I wanted them. Please review when you get a chance - thank you!

**Review by sitaram-kalluri — APPROVED** [review]

**Comment by purnimavenkatasubbu** [comment]
I did a quick sanity of the branch with apps. Attaching the logs.
[addANewContactLogSymmetricKey.txt](https://github.com/atsign-foundation/at_client_sdk/files/11705447/addANewContactLogSymmetricKey.txt)
[atMospherePro_symmetricKey_Sender_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/11705450/atMospherePro_symmetricKey_Sender_logs.txt)
[receiver_symmetric_key_logs.txt](https://github.com/atsign-foundation/at_client_sdk/files/11705453/receiver_symmetric_key_logs.txt)
[wavi_logs_symmetric_key_exchange.txt](https://github.com/atsign-foundation/at_client_sdk/files/11705455/wavi_logs_symmetric_key_exchange.txt)

https://github.com/atsign-foundation/at_client_sdk/assets/43639593/f88484e0-b7d3-43b9-90e4-742328da52d4

NOTE: Test logs of the branch before it got merged into trunk.

**Comment by gkc** [comment]
Thank you @purnimavenkatasubbu !!! Any issues encountered?

**Comment by purnimavenkatasubbu** [comment]
> Thank you @purnimavenkatasubbu !!! Any issues encountered?

No, Gary.

**Comment by gkc** [comment]
Great! Thank you @purnimavenkatasubbu
