### PR TITLE
fix for issue#483

### LINKED ISSUE #483: end2end_tests in at_client_sdk are flaky
**Describe the bug**
Sometimes the end2end_tests fail. Sometimes they succeed.

**To Reproduce**
They're flaky so it's not consistent. However - noticing that end2end_tests had failed for #482, I re-ran them and they failed again. I re-ran them again, and they worked.

**Expected behavior**
The tests should either succeed or fail consistently.

### PR DESCRIPTION
**Pull request by purnimavenkatasubbu**
**- What I did**
Fixed the issue #483 
**- How I did it**
 Generating a new UUID for every test
**- How to verify it**
e2e tests should pass

**- Description for the changelog**

### CODE REVIEW

File: at_end2end_test/test/sharing_key_test.dart [hunk 1]
```diff
@@ -51,20 +51,22 @@ void main() {
...
+    var value = '+91 901920192';
     // Setting currentAtSign atClient instance to context.
     await AtClientManager.getInstance().setCurrentAtSign(
         currentAtSign, namespace, TestUtils.getPreference(currentAtSign));
     var putResult =
-        await currentAtSignClientManager?.atClient.put(phoneKey, value);
+        await currentAtSignClientManager?.atClient.put(phoneNumberKey, value);
     expect(putResult, true);
     var isSyncInProgress = true;
     currentAtSignClientManager?.syncService.sync(onDone: (syncResult) {
```
Comment (VJag) [inline at_end2end_test/test/sharing_key_test.dart:72]: A call to sync is not required for this test. Probably not harmful but not required.

Comment (VJag) [reply at_end2end_test/test/sharing_key_test.dart:72]: The reason I mention this is that app devs are not expected to call sync at all. Sync should happen irrespectively.

**Review by VJag — APPROVED** [review]

**Comment by VJag** [comment]
This PR is good, however, let's remove calls to sync when the expected result can come from the local secondary across any such test.

**Review by gkc — APPROVED** [review]
