### PR TITLE
fix: isInSync bug

### LINKED ISSUE #1444: SyncServiceImpl.isInSync() does not work with APKAM
### Describe the bug

`SyncServiceImpl.isInSync()` creates a new RemoteSecondary each time it is called. The reasons for doing this are not entirely clear, given that `SyncServiceImpl.create()` already creates a RemoteSecondary , but that is another story.

In SyncServiceImpl.create() the enrollmentId is passed to the RemoteSecondary constructor:
```
    remoteSecondary ??= RemoteSecondary(
        atClient.getCurrentAtSign()!, atClient.getPreferences()!,
        atChops: atClient.atChops, enrollmentId: atClient.enrollmentId);
```

However in `SyncServiceImpl.isInSync()` it is not:
```
      remoteSecondary = RemoteSecondary(
          _atClient.getCurrentAtSign()!, _atClient.getPreferences()!,
          atChops: _atClient.atChops);
```

Authentication will then fail, since the enrollmentId must be supplied in order to authenticate with APKAM keys.

### Steps to reproduce

Create a program like this:
```
import 'dart:io';

import 'package:at_cli_commons/at_cli_commons.dart';

Future<void> main(List<String> args) async {
  try {
    var atClient = (await CLIBase.fromCommandLineArgs(args)).atClient;
    await atClient.syncService.isInSync();
    exit(0);
  } catch (e) {
    if (e is ArgumentError) {
      print(CLIBase.argsParser.usage);
    }
    print(e);
    exit(1);
  }
}
```

its dependencies are
```
dependencies:
  at_cli_commons: ^1.3.0
  at_client: ^3.3.0
```

Running it with a PKAM keys file:
```
gary@gkc2019 example % dart bin/is_in_sync_example.dart -a @garycasey -n test
Connecting ... Connected
Is in sync? false
```

Running it with an APKAM keys file:

```
gary@gkc2019 example % dart bin/is_in_sync_example.dart -a @garycasey -k ~/@garycasey.test.mbp.atKeys -n test
Connecting ... Connected
Exception: Exception: Unable to fetch latest server commit id: Exception: Exception: Failed connecting to @garycasey. error:{"errorCode":"AT0401","errorDescription":"Exception: pkam authentication failed"}
```

### Expected behavior

isInSync should also pass enrollmentId to the RemoteSecondary constructor

### Additional context

As part of fixing this I'd also like to see whether we can eliminate isInSync's creation of its own RemoteSecondary

### PR DESCRIPTION
**Pull request by murali-shris**
fixes https://github.com/atsign-foundation/at_client_sdk/issues/1444
**- What I did**
- Fix for isInSync bug in SyncServiceImpl
**- How I did it**
- remove the logic to create new secondary in isInSync method. Re-use _remoteSecondary from create(..) method
- Logic to create new secondary in isInSync was added for an old bug 
https://github.com/atsign-foundation/at_client_sdk/issues/404. This bug is no longer reproducible. Hence removing this logic.
**- How to verify it**
- Tests done
https://github.com/atsign-foundation/at_client_sdk/issues/1444#issuecomment-2532111449

### CODE REVIEW

**Comment by gkc** [comment]
@murali-shris I presume the reason the bug from way back is no longer reproducible is because of [this](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_lookup/lib/src/at_lookup_impl.dart#L595)

File: packages/at_client/lib/src/service/sync_service_impl.dart [hunk 1]
```diff
@@ -539,6 +539,7 @@ class SyncServiceImpl implements SyncService, AtSignChangeListener {
   /// commit-id to sync into the local keystore.
   Future<List<dynamic>> _getEntriesToSyncFromServer(
       int lastReceivedServerCommitId) async {
+    // Sync verb syntax has to be changed before removing these deprecations
```
Comment (gkc) [inline packages/at_client/lib/src/service/sync_service_impl.dart:542]: Can you do a PR in at_lookup to change SyncVerbBuilder so it has default values for the deprecated things; and then do another PR here to remove the deprecated params

**Review by gkc — APPROVED** [review]

**Comment by gkc** [comment]
@murali-shris approved but please see my request above https://github.com/atsign-foundation/at_client_sdk/pull/1448#discussion_r1879803959
