### PR TITLE
fix: git#865 - fixes notifying the switch atSign event multiple times

### LINKED ISSUE #865: AtClientManager notifies multiple times on the switch atSign event.
### Describe the bug

A new instance of classes implementing `AtSignChangeListener` will be added to the `changeListeners` in `AtClientManager` each time we switch back to the same atSign. 
As a result -
 1. on SwichAtSign event, each class will be notified multiple times.
 2. The size of the changeListener list will grow when switching between the events

Further, there is a need to refactor the `AtClientManager.setCurrentAtSign` method. At the moment, the dependencies in the setCurrentAtSign are hard-coded (not injected) and hence there is no way to inject mock objects when writing unit tests.

For instance, we cannot inject mock objects to the AtClient, SyncService and NotificationService in the AtClientManager, which makes it difficult to write the unit tests around switch atSign events.

### Steps to reproduce

1. Onboard wavi app (any app) with two atSign's and switch between the atSign's couple of times.
3. When switching between, the NotificationService and SyncServices are notified multiple times on the switch atSign event.

```
I/flutter ( 4150): FINER|2023-01-04 20:13:57.660988|NotificationServiceImpl|stopping notification listeners for @murali 
I/flutter ( 4150): FINER|2023-01-04 20:13:57.661945|NotificationServiceImpl|stopAllSubscriptions() called - setting monitorIsPaused to true 
I/flutter ( 4150): FINER|2023-01-04 20:13:57.663203|NotificationServiceImpl|removing from _notificationServiceMap: @murali 
I/flutter ( 4150): FINER|2023-01-04 20:13:57.663607|SyncService|stopping stats notification listener for @murali 
I/flutter ( 4150): FINER|2023-01-04 20:13:57.664670|NotificationServiceImpl|stopAllSubscriptions() called - setting monitorIsPaused to true 
I/flutter ( 4150): FINER|2023-01-04 20:13:57.665066|SyncService|removing from _syncServiceMap: @murali 
I/flutter ( 4150): INFO|2023-01-04 20:14:09.861543|AtClientCommitLogCompaction|Stopping commit log compaction job for @murali 
I/flutter ( 4150): INFO|2023-01-04 20:14:09.994331|AtClientCommitLogCompaction|Stopping commit log compaction job for @murali 

I/flutter ( 4150): FINER|2023-01-04 20:14:09.994816|NotificationServiceImpl|stopping notification listeners for @murali 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.997167|NotificationServiceImpl|stopAllSubscriptions() called - setting monitorIsPaused to true 
I/flutter ( 4150): INFO|2023-01-04 20:14:09.998043|Monitor|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.998414|NotificationServiceImpl|@murali monitor is paused. not retrying 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.998780|NotificationServiceImpl|removing from _notificationServiceMap: @murali 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.998995|SyncService|stopping stats notification listener for @murali 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.999146|NotificationServiceImpl|stopAllSubscriptions() called - setting monitorIsPaused to true 
I/flutter ( 4150): FINER|2023-01-04 20:14:09.999612|SyncService|removing from _syncServiceMap: @murali 
I/flutter ( 4150): INFO|2023-01-04 20:14:10.806222|AtClientCommitLogCompaction|Stopping commit log compaction job for @murali 
I/flutter ( 4150): INFO|2023-01-04 20:14:11.334614|AtClientCommitLogCompaction|Stopping commit log compaction job for @murali 
```

### Expected behavior

1. When switching between the atSign's, switch atSign event should be notified only once.

### Screenshots

change_listeners

### Were you using an atApplication when the bug was found?

wavi

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
* Remove the inactive listeners from `AtClientManager._changeListeners` list.
* Add unit tests to assert the changes.
* (gkc) Some further simplifications to code associated with switching atSigns

**- How I did it**
* Added `removeChangeListener` method in AtClientManager, that removes the given instance of AtSignChangeListener from `AtClientManager._changeListeners` list
* In `AtClientManager._notifyListeners` added a line that clones the _changeListeners list and iterate on the cloned list to avoid the concurrent modification exception.
* Some changes to simplify code
    * fix: Added check to SwitchAtSignEvent constructor to prevent events being created when the atClients are the same
    * debug: Added a logger to AtClientManager. Log INFO when switching atSigns
    * refactor: Removed instance variable _previousAtClient from AtClientManager. Instead, determine previousAtClient within the setCurrentAtSign method
    * fix: Added duplicate check to AtClientManager.listenToAtSignChange
    * fix: Changed _currentAtClient from `late` to being nullable to prevent uninitialized check in setCurrentAtSign
    * fix: AtClientManager now calls _notifyListeners before creating the new NotificationServiceImpl and SyncServiceImpl. This allows those classes' implementations of listenToAtSignChange to be simplified
    * refactor: Removed static maps of instances in NotificationServiceImpl and SyncServiceImpl thus allowing some code simplification
    * refactor: Simplified NotificationServiceImpl.listenToAtSignChange
    * refactor: Simplified SyncServiceImpl.listenToAtSignChange, and added code to close the RemoteSecondary's AtLookUp's connection if there is one

**- How to verify it**
* On the switch atSign event, `AtClientManager._changeListeners` should not have obsolete listeners.

**- Description for the changelog**
* Remove the inactive listeners from `AtClientManager._changeListeners` list.

### CODE REVIEW

**Comment by sitaram-kalluri** [comment]
Found the root cause of failing end2end_tests. Will fix the issue and push the changes.

**Review by gkc — DISMISSED** [review]
As discussed just now, we don't need the 'isActive' flag. The concurrent modification error can be eliminated by having `_notifyListeners` make a copy of the _changeListeners and iterate through the copy of the list rather than through the list itself.

As a side note - force-pushing your branch is masking useful information about the evolution of the code - without seeing the interim commits, it was completely unclear to me why the isActive flag was added until we had our discussion. Is there a reason you prefer force-push?

**Comment by sitaram-kalluri** [comment]
> As discussed just now, we don't need the 'isActive' flag. The concurrent modification error can be eliminated by having `_notifyListeners` make a copy of the _changeListeners and iterate through the copy of the list rather than through the list itself.
> 
> As a side note - force-pushing your branch is masking useful information about the evolution of the code - without seeing the interim commits, it was completely unclear to me why the isActive flag was added until we had our discussion. Is there a reason you prefer force-push?

@gkc: Sure, will update the code as per our discussion. I generally do a force push to keep the commit history clean. However, I do it only when there are no review comments/discussions on the PR. If there are review comments/discussions on the PR I avoid doing a force push.

**Comment by gkc** [comment]
> @gkc: Sure, will update the code as per our discussion. I generally do a force push to keep the commit history clean. However, I do it only when there are no review comments/discussions on the PR. If there are review comments/discussions on the PR I avoid doing a force push.

I understand. However sometimes (as in this case), squashing the commits makes it impossible to understand how you got to a particular design / implementation decision, without having a conversation.

**Comment by sitaram-kalluri** [comment]
> > @gkc: Sure, will update the code as per our discussion. I generally do a force push to keep the commit history clean. However, I do it only when there are no review comments/discussions on the PR. If there are review comments/discussions on the PR I avoid doing a force push.
> 
> I understand. However sometimes (as in this case), squashing the commits makes it impossible to understand how you got to a particular design / implementation decision, without having a conversation.

Ok Gary, Will avoid force pushing to the branch.

File: packages/at_client/lib/src/manager/at_client_manager.dart [hunk 1]
```diff
@@ -74,8 +75,26 @@ class AtClientManager {
   }
 
   void _notifyListeners(SwitchAtSignEvent switchAtSignEvent) {
-    for (var listener in _changeListeners) {
+    List<AtSignChangeListener> copyOfChangeListeners = List.from(_changeListeners);
```
Comment (VJag) [inline packages/at_client/lib/src/manager/at_client_manager.dart:92]: Lets add Dart docs for the reason to clone the list

File: packages/at_client/lib/src/manager/at_client_manager.dart [hunk 2]
```diff
@@ -74,8 +75,26 @@ class AtClientManager {
...
+    for (var listener in copyOfChangeListeners) {
       listener.listenToAtSignChange(switchAtSignEvent);
     }
   }
+
+  /// Clears the inactive AtSignChangeListener from the _changeListeners list.
```
Comment (VJag) [inline packages/at_client/lib/src/manager/at_client_manager.dart]: Dart doc should probably say:

Removes the given listener from the list of listeners, that are notified whenever an atSign is switched.

File: packages/at_client/lib/src/service/notification_service_impl.dart [hunk 3]
```diff
@@ -501,6 +504,9 @@ class NotificationServiceImpl
       stopAllSubscriptions();
       _logger.finer(
           'removing from _notificationServiceMap: ${_atClient.getCurrentAtSign()}');
+      _atClientManager.removeChangeListeners(
```
Comment (VJag) [inline packages/at_client/lib/src/service/notification_service_impl.dart]: Unable to comment on an if condition above, just for my understanding, why is the if checking for previous and present atSign to be same?

if (switchAtSignEvent.previousAtClient?.getCurrentAtSign() ==
        _atClient.getCurrentAtSign()) {

Comment (sitaram-kalluri) [reply packages/at_client/lib/src/service/notification_service_impl.dart]: In the above IF condition, _atClient.getCurrentAtSign returns the atSign with which the `NotificationServiceImpl` is created. Since we only wanted to remove the previous atSign (not the new atSign) added the above IF condition.

File: packages/at_client/lib/src/manager/at_client_manager.dart (hunk 2 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/manager/at_client_manager.dart]: Sure Jagan, Will update the dart docs

File: packages/at_client/lib/src/manager/at_client_manager.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/manager/at_client_manager.dart:92]: Sure Jagan, Will add the comments

File: packages/at_client/lib/src/service/notification_service_impl.dart (hunk 3 above)
Comment (VJag) [reply packages/at_client/lib/src/service/notification_service_impl.dart]: Understood the code. Pls add dart docs if it makes sense.

File: packages/at_client/lib/src/manager/at_client_manager.dart [hunk 4]
```diff
@@ -74,8 +75,29 @@ class AtClientManager {
...
+    // concurrent modification exception when removing the previous
+    // atSign listeners
+    List<AtSignChangeListener> copyOfChangeListeners = List.from(_changeListeners);
+    for (var listener in copyOfChangeListeners) {
       listener.listenToAtSignChange(switchAtSignEvent);
     }
   }
+
+  /// Removes the given listener from the _changeListeners list.
+  void removeChangeListeners(AtSignChangeListener atSignChangeListener) {
```
Comment (VJag) [inline packages/at_client/lib/src/manager/at_client_manager.dart:100]: can you change Dart docs to: "Removes the given listener from the list of listeners, that are notified whenever the @sign is switched".

Comment (VJag) [reply packages/at_client/lib/src/manager/at_client_manager.dart:100]: general rule: No impl details in Dart docs

Comment (sitaram-kalluri) [reply packages/at_client/lib/src/manager/at_client_manager.dart:100]: Sure Jagan, will update the dart docs

**Review by VJag — DISMISSED** [review]

**Comment by gkc** [comment]
@VJag Have made some further changes to this branch in https://github.com/atsign-foundation/at_client_sdk/pull/867/commits/0db8b2b8c93708b3459651b4db54ccd718cdb9dd ... please review

**Review by gkc — APPROVED** [review]
