### PR TITLE
fix: Fix intermittent failing compaction job test in functional test

### LINKED ISSUE #1207: at_client functional tests flakiness 2023-01-15
### Describe the bug

See https://github.com/atsign-foundation/at_client_sdk/actions/runs/7527814204/job/20488714969?pr=1206

### Steps to reproduce

See https://github.com/atsign-foundation/at_client_sdk/actions/runs/7527814204/job/20488714969?pr=1206

### Expected behavior

No flakiness

### Screenshots

_No response_

### Smartphones

_No response_

### Were you using an atApplication when the bug was found?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- Fixes https://github.com/atsign-foundation/at_client_sdk/issues/1207
- The primary reason for the problem lies in the background compaction job, which is disrupting the compaction job initiated by the test, leading to discrepancies in the test results.
- The solution to resolve the issue is to stop the background compaction job while executing tests associated with the compaction job.

**- How I did it**
- Introduce `startCompactionJob` and `stopCompactionJob` in AtClientSpec.
- The atClientImpl contains the method implementation to start the compaction job in private. Marked the method as public method.
- Implemented the `stopCompactionJob` method.
- Updated the functional test to stop background compaction job when executing the compaction functional test.

**- How to verify it**
- The functional tests should pass

### CODE REVIEW

File: packages/at_client/lib/src/client/at_client_spec.dart [hunk 1]
```diff
@@ -567,6 +567,21 @@ abstract class AtClient {
...
+  ///
+  /// The [commitLogCompactionTimeIntervalInMins] parameter specifies the time interval,
+  /// in minutes, after which the commit log should be compacted. By default, it is set
+  /// to 11 minutes.
+  ///
+  /// The compaction job removes duplicate entries of a key from the commit log that are already synced
+  /// to the remote secondary. Only the latest commit entry of the key is retained.
+  /// Uncommitted entries that are duplicates will not be removed/compacted.
+  Future<void> startCompactionJob(
+      {int commitLogCompactionTimeIntervalInMins = 11});
```
Comment (gkc) [inline packages/at_client/lib/src/client/at_client_spec.dart]: Please make this parameter a Duration

**Review by gkc — CHANGES_REQUESTED** [review]

File: packages/at_client/lib/src/client/at_client_spec.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/client/at_client_spec.dart]: Sure Gary,

**Comment by sitaram-kalluri** [comment]
The functional and e2e tests fail because monitor fails to start. Attaching the log snippet below. Debugging the issue.

```
INFO|2024-02-21 10:29:34.710734|Monitor (@alice🛠)|status is MonitorStatus.errored : heartbeat will not be sent 

INFO|2024-02-21 10:29:34.794133|Monitor (@alice🛠)|starting monitor for @alice🛠 with lastNotificationTime: 1708511364573 

INFO|2024-02-21 10:29:34.813447|Monitor (@alice🛠)|monitor started for @alice🛠 with last notification time: 1708511364573 

WARNING|2024-02-21 10:29:34.818178|Monitor (@alice🛠)|runZonedGuarded received socket error Converting object to an encodable object failed: Instance of 'Metadata' - calling _handleError 

INFO|2024-02-21 10:29:34.818691|Monitor (@alice🛠)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 

INFO|2024-02-21 10:29:34.818936|Monitor (@alice🛠)|Monitor error Converting object to an encodable object failed: Instance of 'Metadata' - calling the retryCallback 

INFO|2024-02-21 10:29:34.819009|NotificationServiceImpl (@alice🛠)|Monitor retry already queued 

INFO|2024-02-21 10:29:39.787474|Monitor (@alice🛠)|status is MonitorStatus.errored : heartbeat will not be sent 

INFO|2024-02-21 10:29:39.821140|Monitor (@alice🛠)|starting monitor for @alice🛠 with lastNotificationTime: 1708511364573 

INFO|2024-02-21 10:29:39.839429|Monitor (@alice🛠)|monitor started for @alice🛠 with last notification time: 1708511364573 

WARNING|2024-02-21 10:29:39.843379|Monitor (@alice🛠)|runZonedGuarded received socket error Converting object to an encodable object failed: Instance of 'Metadata' - calling _handleError 

INFO|2024-02-21 10:29:39.843647|Monitor (@alice🛠)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 
```

**Comment by sitaram-kalluri** [comment]
> The functional and e2e tests fail because monitor fails to start. Attaching the log snippet below. Debugging the issue.
> 
> ```
> INFO|2024-02-21 10:29:34.710734|Monitor (@alice🛠)|status is MonitorStatus.errored : heartbeat will not be sent 
> 
> INFO|2024-02-21 10:29:34.794133|Monitor (@alice🛠)|starting monitor for @alice🛠 with lastNotificationTime: 1708511364573 
> 
> INFO|2024-02-21 10:29:34.813447|Monitor (@alice🛠)|monitor started for @alice🛠 with last notification time: 1708511364573 
> 
> WARNING|2024-02-21 10:29:34.818178|Monitor (@alice🛠)|runZonedGuarded received socket error Converting object to an encodable object failed: Instance of 'Metadata' - calling _handleError 
> 
> INFO|2024-02-21 10:29:34.818691|Monitor (@alice🛠)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 
> 
> INFO|2024-02-21 10:29:34.818936|Monitor (@alice🛠)|Monitor error Converting object to an encodable object failed: Instance of 'Metadata' - calling the retryCallback 
> 
> INFO|2024-02-21 10:29:34.819009|NotificationServiceImpl (@alice🛠)|Monitor retry already queued 
> 
> INFO|2024-02-21 10:29:39.787474|Monitor (@alice🛠)|status is MonitorStatus.errored : heartbeat will not be sent 
> 
> INFO|2024-02-21 10:29:39.821140|Monitor (@alice🛠)|starting monitor for @alice🛠 with lastNotificationTime: 1708511364573 
> 
> INFO|2024-02-21 10:29:39.839429|Monitor (@alice🛠)|monitor started for @alice🛠 with last notification time: 1708511364573 
> 
> WARNING|2024-02-21 10:29:39.843379|Monitor (@alice🛠)|runZonedGuarded received socket error Converting object to an encodable object failed: Instance of 'Metadata' - calling _handleError 
> 
> INFO|2024-02-21 10:29:39.843647|Monitor (@alice🛠)|socket.listen onDone called. Will destroy socket, set status stopped, call retryCallback 
> ```

Found the root cause of the issue:

When `pubKeyHash` is null, `toJson` method is invoked which is leading to failure. Attaching the error stack trace below.

#0      Metadata.toJson (package:at_commons/src/keystore/at_key.dart:687:60)
#1      _defaultToEncodable (dart:convert/json.dart:627:55)
#2      _JsonStringifier.writeObject (dart:convert/json.dart:787:36)
#3      _JsonStringifier.writeMap (dart:convert/json.dart:874:7)
#4      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829:21)
#5      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
#6      _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
#7      _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
#8      JsonEncoder.convert (dart:convert/json.dart:345:30)
#9      JsonCodec.encode (dart:convert/json.dart:231:45)
#10     jsonEncode (dart:convert/json.dart:114:10)
#11     NotificationServiceImpl._internalNotificationCallback (package:at_client/src/service/notification_service_impl.dart:236:15)
<asynchronous suspension>

**Comment by sitaram-kalluri** [comment]
All tests passed after retracting at_commons 4.0.2 version.

**Review by gkc — APPROVED** [review]
