### PR TITLE
fix: NotificationService.subscribe fails to return existing listener on same regex.

### LINKED ISSUE #684: NotificationService.subscribe fails to return existing listener on same regex
**Describe the bug**
When trying to reproduce the following issue: https://github.com/atsign-foundation/at_client_sdk/issues/661, Found that the notification service-> subscribe method fails to return the existing listener when already present. Instead creates a new StreamController.

The root cause of the issue is we are check on String (regex) instead of comparing on the NotificationConfig object. Below is the code snippet.

```dart
if (_streamListeners.containsKey(regex)) {
```

Fix:
Modify the streamListeners from Map to HashMap and overrides the equal and hashcode methods to compare the NotificationConfig Object.

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
- Fix the issue of single notification being sent for multiple times.

  **-Root cause**
  At the moment, NotificationService.subscribe returns a Stream.broadcast which supports multiple listeners. From the app,
 `NotificationService.subscribe` method is being invoked multiple time's with same regex which leads to the same notification being fetched in the listen callback.

  **-Fix**
  - Replace the Stream.broadcast with simple Streams which supports only single listener. If subscribed for the second time, 
  throws a `Bad State. stream was already listened to`(This will **NOT** cause the app to crash). 
  - Ideally, for a given regex, having a single listener would suffice and i do not see a scenario which would require multiple 
  listeners for the same regex. Please share your thoughts on this? 
 
**- How I did it**
- Replace the Stream.broadcast with simple Streams.
- Replace the Map with HaspMap and override the equals and hashcode methods to compare the NotificationConfig object on regexes.

**- How to verify it**
- The Notification should be sent to app only once.
- If a NotificationService.subscribe is invoked for more than once, then a `Bad State` erorr would be thrown.

**- Description for the changelog**

### CODE REVIEW

**Comment by sitaram-kalluri** [comment]
The e2e tests have failed because KeyStream tests have multiple subscriptions causing Bad State: Stream is already listened to. Basing on the dicsussion in the internal stand-up will refactor the changes.

**Comment by gkc** [comment]
@kalluriramkumar checks are failing ...

**Review by gkc — CHANGES_REQUESTED** [review]
Checks are failing

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar checks are failing ...

Yes Gary, At the moment, the KeyStream tests are have multiple listeners, hence the tests the are failing. Wanted to check if the removing the broadcast (Changing Stream.broadcast to simple stream) is fine. If yes, will refactor the tests.

**Comment by sitaram-kalluri** [comment]
@XavierChanth : I am not sure on which apps are using KeyStreams. Request your feedback/thoughts on changing the Stream.broadcast to simple streams.

**Comment by xavierchanth** [comment]
For root cause:
Is the subscription being invoked multiple times in our client code, or is it an app developer mistake causing the problem?
If client code, then I think we should seek to fix the problem of multiple invocations, here's why:

Keep in mind the following from dart docs:

> Single-subscription streams are generally used for streaming chunks of larger contiguous data, like file I/O.
> 
> A broadcast stream allows any number of listeners, and it fires its events when they are ready, whether there are listeners or not.

Notifications are event driven, and ideally should be using broadcast streams.
From a Flutter development perspective, it is useful to be able to subscribe from multiple places, to reduce the need for unnecessary re-renders of certain widgets.

Despite all of this, if we still decide to opt into single-subscription streams:
KeyStream will need to be refactored so that it does not need to subscribe to the notification service. This will most likely require coupling notification service and key stream, which is less ideal.

**Comment by sitaram-kalluri** [comment]
> For root cause: Is the subscription being invoked multiple times in our client code, or is it an app developer mistake causing the problem? If client code, then I think we should seek to fix the problem of multiple invocations, here's why:
> 
> Keep in mind the following from dart docs:
> 
> > Single-subscription streams are generally used for streaming chunks of larger contiguous data, like file I/O.
> > A broadcast stream allows any number of listeners, and it fires its events when they are ready, whether there are listeners or not.
> 
> Notifications are event driven, and ideally should be using broadcast streams. From a Flutter development perspective, it is useful to be able to subscribe from multiple places, to reduce the need for unnecessary re-renders of certain widgets.
> 
> Despite all of this, if we still decide to opt into single-subscription streams: KeyStream will need to be refactored so that it does not need to subscribe to the notification service. This will most likely require coupling notification service and key stream, which is less ideal.

@XavierChanth : It is from the app's code the multiple requests coming in and communicated to the app developer. Putting Stream.broadcast back in-place.

File: at_client/test/notification_service_test.dart [hunk 1]
```diff
@@ -381,4 +381,26 @@ void main() {
           NotificationStatusEnum.undelivered);
     });
   });
+
+  group('A group of tests to validate notification subscribe method', () {
+    test('A subscribe returns a new stream for a new regex', () async {
```
Comment (gkc) [inline at_client/test/notification_service_test.dart]: Tests should have explicit assertions / expectations.

**Review by gkc — CHANGES_REQUESTED** [review]

File: at_client/test/notification_service_test.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply at_client/test/notification_service_test.dart]: Modified the tests to assert on the size of the streamListeners map to verify if a new instances is being created or not.

**Review by gkc — APPROVED** [review]
