### PR TITLE
test: Fix failing functional tests due to sync race conditions

### LINKED ISSUE #840: test: functional test atclient_sharedkey_test.dart is occasionally failing
### Describe the bug

functional test atclient_sharedkey_test.dart is occasionally failing

### Steps to reproduce

Has happened at least twice in the past three days. It eventually fails after a three minute timeout. 

### Expected behavior

test should pass. Likely a race condition related to checking if sync is complete.

### PR DESCRIPTION
**Pull request by purnimavenkatasubbu**
**- What I did**
I added a check to see if syncStatus is a success && localCommitId equals serverCommitID. If both are equal, Exit the code as sync completed.
Exit if sync process exceeds 30 seconds
Call sync again if localCommitId is not equal to server commit id.
**- How I did it**
Added a condition to see if localCommiId equals serverCommitI

**- How to verify it**
all the functional tests should pass
**- Description for the changelog**

### CODE REVIEW

File: tests/at_functional_test/test/atclient_sync_callback_test.dart [hunk 1]
```diff
@@ -166,57 +166,26 @@ void main() {
...
-            expect(keyInfo.syncDirection, SyncDirection.remoteToLocal);
-          }
-        });
-      }
-      // At the end of the test (either in first run or by end of second run),
-      // localCommitId should be equal to serverCommitId
-      if (isLocalCommitIdEqualServerCommitId == false) {
-        if (syncProgress.localCommitId == syncProgress.serverCommitId) {
-          isLocalCommitIdEqualServerCommitId = true;
+      expect(syncProgress.keyInfoList, isNotEmpty);
```
Comment (sitaram-kalluri) [inline tests/at_functional_test/test/atclient_sync_callback_test.dart]: Intermittently, sync progress returns localCommitId and serverCommitId as null in which case the keyInfoList will be empty. Then the "expect" fails. 
Please surround "expect" inside an IF condition as follows:
```dart
if (syncProgress.localCommitIdBeforeSync != syncProgress.localCommitId) {
    expect(syncProgress.keyInfoList, isNotEmpty);
    expect(syncProgress.localCommitId,
          greaterThan(syncProgress.localCommitIdBeforeSync!));
}

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: tests/at_functional_test/lib/src/sync_service.dart [hunk 2]
```diff
@@ -18,20 +19,39 @@ class FunctionalTestSyncService {
   }
 
   Future<void> syncData(SyncService syncService) async {
-    var isSyncInProgress = true;
-    var functionalTestSyncProgressListener = FunctionalTestSyncProgressListener();
+    // Setting sync request threshold to 1 to expedite sync process
```
Comment (sitaram-kalluri) [inline tests/at_functional_test/lib/src/sync_service.dart:23]: It would be nice to have "SyncOptions" as an optional parameter to the "syncData" method similar to the way we have in E2E tests. So that we can have tests wait on a specific key to sync before asserting.

**Review by sitaram-kalluri — CHANGES_REQUESTED** [review]

File: tests/at_functional_test/test/atclient_sync_callback_test.dart (hunk 1 above)
Comment (purnimavenkatasubbu) [reply tests/at_functional_test/test/atclient_sync_callback_test.dart]: Updated

**Review by sitaram-kalluri — APPROVED** [review]
