### PR TITLE
fix: Invalid key in sync causes infinite loop

### LINKED ISSUE #955: Sync failing to complete due to incomplete handling of exceptions that the client may encounter
See https://github.com/atsign-foundation/at_client_sdk/issues/951 for context

The client SyncService should handle any exception it encounters while writing data locally, and ensure that the sync never gets stuck in a loop

### PR DESCRIPTION
**Pull request by sitaram-kalluri**
**- What I did**
* Fix sync running into an infinite loop when an invalid key is sent from the server in the sync response.

**- How I did it**
* Introduce a new variable "lastReceivedServerCommitId" which keeps track of the last commit entry sent by the server. When fetching the next sent of entries to sync, the client sends the "lastReceivedServerCommitId" instead of "lastSyncedCommitId" into the local keystore.

**- How to verify it**
* Updated the unit tests to accommodate the changes.

**- Description for the changelog**
* Fix: Sync running into infinite loop when an invalid key is present in the entries to sync into client

### CODE REVIEW

File: packages/at_client/lib/src/service/sync_service_impl.dart [hunk 1]
```diff
@@ -748,6 +772,22 @@ class SyncServiceImpl implements SyncService, AtSignChangeListener {
...
   }
 
+  Future<int> _getLastReceivedServerCommitId() async {
+    // If "lastReceivedServerCommitId" key exists, fetch the data and return the
+    // last received server commit id.
+    var isLastReceivedServerKeyExists = _atClient
+        .getLocalSecondary()!
+        .keyStore!
+        .isKeyExists(_lastReceivedServerCommitIdAtKey.toString());
+    if (isLastReceivedServerKeyExists) {
```
Comment (murali-shris) [inline packages/at_client/lib/src/service/sync_service_impl.dart]: can we simplify the method like this
try  {
var response = await _atClient.get(_lastReceivedServerCommitIdAtKey);
      return int.parse(response.value);
} on KeyNotFoundException {
 return _getLocalCommitId();
}

File: packages/at_client/lib/src/service/sync_service_impl.dart [hunk 2]
```diff
@@ -406,93 +409,111 @@ class SyncServiceImpl implements SyncService, AtSignChangeListener {
...
-        break;
-      }
-      // Iterates over each commit
-      for (dynamic serverCommitEntry in syncResponseJson) {
-        _sendTelemetry('_syncFromServer.forEachEntry.start', {
-          "atKey": serverCommitEntry['atKey'],
-          "operation": serverCommitEntry['operation'],
-          "commitId": serverCommitEntry['commitId'],
+    try {
+      while (serverCommitId > lastReceivedServerCommitId) {
```
Comment (murali-shris) [inline packages/at_client/lib/src/service/sync_service_impl.dart:422]: what will happen here when initially there is connection to perform sync and in between sync connection drops.

**Review by murali-shris — APPROVED** [review]

**Review by murali-shris — CHANGES_REQUESTED** [review]
re-request

File: packages/at_client/lib/src/service/sync_service_impl.dart (hunk 1 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/service/sync_service_impl.dart]: Sure Murali

File: packages/at_client/lib/src/service/sync_service_impl.dart (hunk 2 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/service/sync_service_impl.dart:422]: In "_syncFromServer" method, the lastReceivedServerCommitId is updated at the end of the batch response. The logic to update the lastReceivedServerCommitId is wrapped inside a "finally" block to ensure the lastReceivedServerCommitId is updated even if an exception occurs.

So, When network drops or if sync stops in between, the lastReceivedServerCommitId is presisted and in the next run, the lastReceivedServerCommitId is fetched and request the server for the commit entries from that point.

File: packages/at_client/lib/src/service/sync_service_impl.dart [hunk 3]
```diff
@@ -59,6 +59,9 @@ class SyncServiceImpl implements SyncService, AtSignChangeListener {
   /// Returns the currentAtSign associated with the SyncService
   String get currentAtSign => _atClient.getCurrentAtSign()!;
 
+  /// A local AtKey to persist the last received server commitId
+  late AtKey _lastReceivedServerCommitIdAtKey;
```
Comment (gkc) [inline packages/at_client/lib/src/service/sync_service_impl.dart]: Please mark this variable as final as well as late

**Review by gkc — CHANGES_REQUESTED** [review]
Mainly LGTM. Have left a request for a small change and have two questions
1. Have you tested using an app?
2. Are there unit tests which simulate the server sending 'invalid' keys in the sync response?

**Comment by sitaram-kalluri** [comment]
> Mainly LGTM. Have left a request for a small change and have two questions
> 
> 1. Have you tested using an app?
> 2. Are there unit tests which simulate the server sending 'invalid' keys in the sync response?

On 1. I am tested with the buzz app, Yet to test with wavi app.
On 2. Added a unit test to assert sync do no enter into infinite loop when there is a bad key in sync response.

File: packages/at_client/lib/src/service/sync_service_impl.dart (hunk 3 above)
Comment (sitaram-kalluri) [reply packages/at_client/lib/src/service/sync_service_impl.dart]: Sure Gary.

**Review by gkc — APPROVED** [review]

**Review by murali-shris — APPROVED** [review]
